# Generated by Django 3.2.2 on 2021-08-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('salary', models.CharField(default='unpaid', max_length=100)),
                ('typeofwork', models.CharField(max_length=50)),
                ('startdate', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=10)),
                ('applyby', models.CharField(max_length=10)),
            ],
        ),
    ]
