# Generated by Django 3.2.2 on 2021-08-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc1', '0002_auto_20210827_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='startdate',
            new_name='begin',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='title',
            new_name='task',
        ),
    ]
